uploads = []
generated = []

[[outputs]]
id = "X6EvKWmG0oeYza5mDjGPn"
uri = "file://origins_chaos_addon_2.0.0.zip"
type = "unspecified"
title = "Origins: Chaos Addon v2.0.0 — NeoForge 1.21.1"

[[outputs]]
id = "Sue3MsXMBAlUeNdJrmdLm"
uri = "file://chaos_addon_output/build/libs/chaos_addon-2.0.0.tar.gz"
type = "unspecified"
title = "chaos_addon-2.0.0.jar"
